// <auto-generated />
namespace Project_Speaker.Migrations.SpeakerDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ScriptN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScriptN));
        
        string IMigrationMetadata.Id
        {
            get { return "202402032103056_ScriptN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
